apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: demo-app
  namespace: demo-app-ns
  labels:
    app.kubernetes.io/name: demo-app
    app.kubernetes.io/component: autoscaling

spec:
  hosts:
    - demo.local

  scaleTargetRef:
    name: demo-app
    kind: Deployment
    service: demo-app
    port: 80

  replicas:
    min: 0
    max: 10

  scalingMetric:
    requestRate:
      targetValue: 10
      window: 1m