apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: keda
  namespace: argocd

spec:
  project: default

  sources:

    # ==========================================================
    # KEDA HELM CHART
    # ==========================================================
    - repoURL: https://kedacore.github.io/charts
      chart: keda
      targetRevision: 2.21.0

      helm:
        valueFiles:
          - $values/values/keda-values.yaml

    # ==========================================================
    # GIT REPOSITORY - CUSTOM VALUES
    # ==========================================================
    - repoURL: https://github.com/LeelaNaveen123-Git/keda-argocd.git
      targetRevision: main
      ref: values

  # ============================================================
  # DESTINATION
  # ============================================================
  destination:
    server: https://kubernetes.default.svc
    namespace: keda

  # ============================================================
  # SYNC POLICY
  # ============================================================
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true