apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-http-addon
  namespace: argocd

spec:
  project: default

  sources:

    # Helm chart
    - repoURL: https://kedacore.github.io/charts
      chart: keda-add-ons-http
      targetRevision: 0.16.0

      helm:
        valueFiles:
          - $values/values/keda-http-addon-values.yaml

    # Git repository containing custom values
    - repoURL: https://github.com/LeelaNaveen123-Git/keda-argocd.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: keda

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true